# Generated by Django 4.2.18 on 2025-03-17 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(default='/images/default.jpg', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('Patron', 'Patron'), ('Librarian', 'Librarian')], default='Patron', max_length=20),
        ),
    ]
