# Generated by Django 4.2.18 on 2025-03-15 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('Patron', 'Patron'), ('Librarian', 'Librarian')], default='Patron', max_length=20),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='')),
                ('user', models.ForeignKey(max_length=10, on_delete=django.db.models.deletion.CASCADE, to='home.userprofile')),
            ],
        ),
    ]
