# Generated by Django 4.2.18 on 2025-04-11 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_userprofile_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='real_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
