# Generated by Django 4.2.18 on 2025-03-16 02:46

from django.db import migrations
import s3direct.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_userprofile_profile_pic_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=s3direct.fields.S3DirectField(blank=True),
        ),
    ]
