# Generated by Django 4.2.18 on 2025-03-17 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='image_url',
        ),
        migrations.AddField(
            model_name='game',
            name='image',
            field=models.ImageField(default='/images/default.jpg', upload_to='game_images/'),
        ),
    ]
