# Generated by Django 4.2.18 on 2025-03-26 17:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("catalog", "0002_remove_game_image_url_game_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="game",
            name="platform",
            field=models.CharField(default="Unknown", max_length=100),
        ),
        migrations.AddField(
            model_name="game",
            name="release_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="game",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="game", name="description", field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="game",
            name="genre",
            field=models.CharField(default="Unknown", max_length=100),
        ),
        migrations.AlterField(
            model_name="game",
            name="image",
            field=models.ImageField(upload_to="game_images/"),
        ),
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("is_private", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "games",
                    models.ManyToManyField(
                        related_name="collections", to="catalog.game"
                    ),
                ),
            ],
        ),
    ]
