# Generated by Django 4.2.18 on 2025-04-12 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_delete_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='upc',
            field=models.CharField(blank=True, editable=False, max_length=12, unique=True),
        ),
    ]
