# Generated by Django 4.2.18 on 2025-04-12 23:53

from django.db import migrations, models
import uuid

def generate_upc(apps, schema_editor):
    Game = apps.get_model('catalog', 'Game')
    for game in Game.objects.all():
        if not game.upc:
            game.upc = str(uuid.uuid4())[:12]
            game.save()

class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_delete_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='upc',
            field=models.CharField(max_length=12, null=True, blank=True, editable=False),
        ),
        migrations.RunPython(
            generate_upc,
            reverse_code=migrations.RunPython.noop
        ),
        migrations.AlterField(
            model_name='game',
            name='upc',
            field=models.CharField(max_length=12, unique=True, editable=False),
        ),
    ]
