# Generated by Django 4.2.18 on 2025-04-13 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_game_upc'),
        ('catalog', '0005_loan_borrowrequest'),
    ]

    operations = [
    ]
