# Generated by Django 4.2.18 on 2025-04-13 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_alter_game_upc_comment_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="location",
            field=models.CharField(
                default="Main Library",
                help_text="Physical location of the game",
                max_length=100,
            ),
        ),
    ]
