# Generated by Django 4.2.18 on 2025-04-13 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0008_game_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="location",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
