# Generated by Django 4.2.18 on 2025-04-22 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0010_alter_game_description_alter_game_genre_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="borrowrequest",
            name="duration_days",
            field=models.IntegerField(
                choices=[
                    (7, "1 Week"),
                    (14, "2 Weeks"),
                    (21, "3 Weeks"),
                    (28, "4 Weeks"),
                ],
                default=14,
            ),
        ),
    ]
